services:
    tor-snowflake-proxy:
        image: "thetorproject/snowflake-proxy:${IMAGE_TAG:-latest}"
        container_name: ${SERVICE_NAME}
        restart: unless-stopped
        network_mode: host

        command:
            - "-capacity"
            - "5"
            - "-ephemeral-ports-range"
            - "30000:50000"
